server:
  address: ":6006"
routes:
  - name: 测试 1
    pattern: "ser1"
    target: "http://127.0.0.1:7001"
  - name: 测试 2
    pattern: "ser2"
    target: "http://127.0.0.1:7002"
  - name: ollama服务器
    pattern: "ollama"
    target: "http://127.0.0.1:11434"
  - name: xinfer服务器
    pattern: "xinfer"
    target: "http://127.0.0.1:9997"